---
abstract: 'Combine data and logic in YAML'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: YAML-Active
provides:
  YAML::Active:
    file: lib/YAML/Active.pm
    version: 1.100810
  YAML::Active::Concat:
    file: lib/YAML/Active.pm
    version: 1.100810
  YAML::Active::Eval:
    file: lib/YAML/Active.pm
    version: 1.100810
  YAML::Active::Include:
    file: lib/YAML/Active.pm
    version: 1.100810
  YAML::Active::Plugin:
    file: lib/YAML/Active/Plugin.pm
    version: 1.100810
  YAML::Active::Plugin::Array:
    file: lib/YAML/Active/Plugin/Array.pm
    version: 1.100810
  YAML::Active::Plugin::Hash:
    file: lib/YAML/Active/Plugin/Hash.pm
    version: 1.100810
  YAML::Active::Print:
    file: lib/YAML/Active.pm
    version: 1.100810
  YAML::Active::Shuffle:
    file: lib/YAML/Active.pm
    version: 1.100810
  YAML::Active::ValueMutator:
    file: lib/YAML/Active.pm
    version: 1.100810
  YAML::Active::lc:
    file: lib/YAML/Active.pm
    version: 1.100810
  YAML::Active::uc:
    file: lib/YAML/Active.pm
    version: 1.100810
requires:
  Carp: 0
  Class::Accessor::Complex: 0
  English: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.88
  YAML::XS: 0
  constant: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=YAML-Active
  homepage: http://search.cpan.org/dist/YAML-Active/
  repository: http://github.com/hanekomu/YAML-Active
version: 1.100810
